# Generated by Django 4.0.4 on 2022-04-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producttypeone',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producttypethree',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producttypetwo',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category'),
        ),
        migrations.AlterField(
            model_name='producttypeone',
            name='categories',
            field=models.ManyToManyField(to='product.category'),
        ),
        migrations.AlterField(
            model_name='producttypethree',
            name='categories',
            field=models.ManyToManyField(to='product.category'),
        ),
        migrations.AlterField(
            model_name='producttypetwo',
            name='categories',
            field=models.ManyToManyField(to='product.category'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
